name: tracker_app_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+4

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.2.0
  flutter_svg: ^2.2.3
  geolocator: ^14.0.2
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  google_maps_flutter: ^2.14.0
  latlong2: ^0.9.1
  permission_handler: ^12.0.1
  socket_io_client: ^3.1.4
  widget_to_marker: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  
  # Para Android - Adaptive Icon (recomendado)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  
  # Opcional: Remover el icono antiguo
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/map_styles/
